env:
  global:
    - secure: "STh57xr3JMtAsGyfHFwVS4OlKV6x2kGBM+kmYCMREG8Kp0Fhz0lB92t+uNO1Xa8ITptvCVvDTQj4bzBrykaTMrnj8AhvhcWBiu5TTJHBTYnLQqPoVdVXkJ4FeXTdrHmXumar3SYZ4xWOFC7RMqtBSF6i+lAWKD6fpWG+QeFLvTxjONfgtDlWa8a4wEiuDOlUmThSH8POnoE6w0N0q4V6G1B5AmK7XOASwwm5+5oMVI3kYEGX/mtLynNetF1eL4zAQxPbtAOtpAFtj7U1hIxTUXSGdWD384floyFfJ1qM2kfBCbwTuXF8+d532Hw/4Mit4FKRnfE6YU/cA6cu1auk0AY+r8yP1lygWORKEunfmoGGIYFrjDktZ4j96SY/Tzea5zMGVy/yGuz8eBwOFAQp45PZ92v188UddQXTGvwbM5WTi9INJlLzubpttRULc1WVSc+4c206pa+MZp9nA8potAp1RO5VBp+ysu6jO6HrnOzQ92xBMO/9ds9M4lY8kpWpmNvNKvzgomXoUXV3AY1FCc9p5MsnL/o8v/GOe3H4xLL9pcj3IX/sTnE7UWzENTvdXTsV1jR4foDQyVLpK2Exrs3FSy5hSIS4RE7TXrcYmxHL1rUjk+PE8UzlgAuhmeP6CcLIbsnkCTUtKwkqKFxYtVoEpWC8NeO8BtVIh6/4Fjg="
    - secure: "Xl2/U/zTbir63KqK4hzOkIYDiNwPuD6LMbpvp6Pd2ZBVms17uX2chKCFE0iPeuK9zyUr37YNnpPEFujcx0g4+cbPJf8Wjoxg/9CiK+nH3PG9WCruMQO4UrNg6Rne4Mce1IO3Xdxwkt4WoV8XA8R701YYB59GiEinCb4SEsGXiVFV7n8/ha+6WwvDfkVaQUJiGAUsbqk6mJGKLIF1s0LLxYDX17jgZDKKfKD05SkpGz37o93DRhyxz5ylZukn53DzBjMVSRVr8XzNfvrNQCndwc7oeKiwXntMw2s/xCsVLDL+mRO7g4o0QDjrKsybwpt7YtkK57F8E/p5ryglDgrApRcc4taU29Gq7w25IGGMoElR3r2NRLISGPgiVOJo4j6KvmifPp8XLxncQAcAvt/ce7cXpt80/esk5hBHT47fkLD1m1Q6N/2ZhbGrrRK+H201heKepfMgCLelLGmK58EHQU4a4Rgn4h7RxoF+MJZD445spr3KA+kMzs5G1Hhn1V0KMt3FoU5GqhzyIdGODcHcRMIVGXiUXOHUJJsDjh1F0uMxM59h9pd2yhkxLJlVyodwlUEv0dAXUl5XYykkUD/U51IIiatC97yrkEJAWvneKp2UXpCdmJO4S3SBERZ4v7d2A3j0dTXaQUutyh/zQuEqPzVkU4DZM3bkBLWwOk0Y160="
language: java
sudo: false
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
script:
  - cd releng/net.sourceforge.plantuml.aggregator
  - mvn clean install
